parameters:
- name: JobName
  type: string
  default: 'Perf'
- name: LinuxPool
  type: string
  default: 'azsdk-pool-mms-ubuntu-2004-perf'
- name: LinuxVmImage
  type: string
  default: 'MMSUbuntu20.04'
- name: WindowsPool
  type: string
  default: 'azsdk-pool-mms-win-2019-perf'
- name: WindowsVmImage
  type: string
  default: 'MMS2019'
- name: Language
  type: string
  default: ''
- name: LanguageVersion
  type: string
  default: ''
- name: LanguageRepoName
  type: string
  default: $(Build.Repository.Name)
- name: LanguageRepoCommitish
  type: string
  default: $(Build.SourceVersion)
- name: ToolsRepoCommitish
  type: string
  default: 'main'
- name: Variables
  type: object
  default: []
- name: OperatingSystems
  type: string
  default: 'Linux'
- name: InstallLanguageSteps
  type: stepList
  default: []
- name: ServiceDirectory
  type: string
  default: ''
- name: PackageVersions
  type: string
  default: '.*'
- name: Tests
  type: string
  default: '^.*$'
- name: Arguments
  type: string
  default: '.*'
- name: Iterations
  type: number
  default: '5'
- name: Profile
  type: boolean
  default: false
- name: AdditionalArguments
  type: string
  default: ''
- name: EnvVars
  type: object
  default: {}
- name: UsePlatformContainer
  type: boolean
  default: false
- name: DependsOn
  type: string
  default: ''
- name: Matrix
  type: string
- name: CloudConfig
  type: object
  default: {}

jobs:
- job:
  dependsOn: ${{ parameters.DependsOn }}
  condition: ne(${{ parameters.Matrix }}, '{}')
  strategy:
    matrix: $[ ${{ parameters.Matrix }} ]
  pool:
    name: $(Pool)
    vmImage: $(OSVmImage)

  ${{ if eq(parameters.UsePlatformContainer, 'true') }}:
      container: $[ variables['Container'] ]

  timeoutInMinutes: 360
  variables:
  - ${{ parameters.Variables }}
  - name: Profile
    ${{ if parameters.Profile }}:
      value: '--profile'
    ${{ else }}:
      value: ''
  steps:

  - template: /eng/common/pipelines/templates/steps/sparse-checkout.yml
    parameters:
      Paths:
      - '/*'
      - '!sdk/**/test-recordings/*'
      - '!sdk/**/recordings/*'
      - '!sdk/**/SessionRecords/*'
      - '!sdk/**/session-records/*'
      Repositories:
      - Name: ${{ parameters.LanguageRepoName }}
        Commitish: ${{ parameters.LanguageRepoCommitish }}
        WorkingDirectory: $(System.DefaultWorkingDirectory)
      - Name: Azure/azure-sdk-tools
        Commitish: ${{ parameters.ToolsRepoCommitish }}
        WorkingDirectory: $(System.DefaultWorkingDirectory)/azure-sdk-tools

  - template: /eng/common/pipelines/templates/steps/verify-agent-os.yml
    parameters:
      AgentImage: $(OSVmImage)

  - ${{ parameters.InstallLanguageSteps }}

  - template: /eng/common/TestResources/deploy-test-resources.yml
    parameters:
      ServiceDirectory: ${{ parameters.ServiceDirectory }}
      Location: westus
      ResourceType: perf

  - script: >-
      dotnet run -- run
      --language ${{ parameters.Language }}
      --language-version ${{ parameters.LanguageVersion }}
      --repo-root $(System.DefaultWorkingDirectory)
      --tests-file $(System.DefaultWorkingDirectory)/sdk/${{ parameters.ServiceDirectory }}/perf-tests.yml
      --package-versions "${{ parameters.PackageVersions }}"
      --tests "$(Tests)"
      --arguments "${{ parameters.Arguments }}"
      --iterations ${{ parameters.Iterations }}
      $(Profile)
      ${{ parameters.AdditionalArguments }}
    workingDirectory: azure-sdk-tools/tools/perf-automation/Azure.Sdk.Tools.PerfAutomation
    env:
      ${{ each var in parameters.EnvVars }}:
        ${{ var.key }}: ${{ var.value }}
    displayName: Run perf tests

  - pwsh: |
      get-content results.txt
    workingDirectory: azure-sdk-tools/tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/results
    displayName: Print results.txt
    condition: always()

  - pwsh: |
      get-content results.csv
    workingDirectory: azure-sdk-tools/tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/results
    displayName: Print results.csv
    condition: always()

  - pwsh: |
      get-content results.md
    workingDirectory: azure-sdk-tools/tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/results
    displayName: Print results.md
    condition: always()

  - pwsh: |
      get-content results.json
    workingDirectory: azure-sdk-tools/tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/results
    displayName: Print results.json
    condition: always()

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: azure-sdk-tools/tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/results
      artifactName: results-${{ parameters.Language }}-$(System.JobName)
    condition: always()

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(System.DefaultWorkingDirectory)/${{ parameters.Language }}-profile.zip
      artifactName: ${{ parameters.Language }}-profile.zip
    condition: ${{ parameters.Profile }}

  - template: /eng/common/TestResources/remove-test-resources.yml
    parameters:
      ServiceDirectory: ${{ parameters.ServiceDirectory }}
      ResourceType: perf
