emit:
  - "@azure-tools/typespec-ts"
options:
  "@azure-tools/typespec-ts":
    azureSdkForJs: false
    generateMetadata: false
    generateTest: false
    "emitter-output-dir": "{project-root}/../batch-rest/"
    packageDetails:
      name: "@azure-rest/batch"
      description: "Batch Service Rest Level Client"
      version: "1.0.0-beta.1"
